"""add nhom_ti_le to blueprint_cells

Revision ID: be63bb860100
Revises: d0f98e7662d7
Create Date: 2026-07-09 02:37:32.500981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be63bb860100'
down_revision: Union[str, Sequence[str], None] = 'd0f98e7662d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint_cells', sa.Column('nhom_ti_le', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprint_cells', 'nhom_ti_le')
    # ### end Alembic commands ###
